[build]
  command = "npm run build"
  # Let @netlify/plugin-nextjs handle the publish directory automatically

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove manual redirects - let Next.js plugin handle routing 